sudo: required
services:
  - docker
  
before_install:
  - docker build -t bradwtracy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bradwtracy/react-test npm test
  
after_success:
  - docker build -t bradwtracy/multi-client ./client
  - docker build -t bradwtracy/multi-nginx ./nginx
  - docker build -t bradwtracy/multi-server ./server
  - docker build -t bradwtracy/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
  # Take those images and push them to docker hub
  - docker push bradwtracy/multi-client
  - docker push bradwtracy/multi-nginx
  - docker push bradwtracy/multi-server
  - docker push bradwtracy/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-040698126140
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

